INSERT INTO TB_SEGMENTS (ID_SEGMENTS, NAME_SEGMENTS) VALUES (SEGMENTS_SEQ.NEXTVAL, 'Viagens');
INSERT INTO TB_SEGMENTS (ID_SEGMENTS, NAME_SEGMENTS) VALUES (SEGMENTS_SEQ.NEXTVAL, 'Comida');
INSERT INTO TB_SEGMENTS (ID_SEGMENTS, NAME_SEGMENTS) VALUES (SEGMENTS_SEQ.NEXTVAL, 'Videogames');
INSERT INTO TB_SEGMENTS (ID_SEGMENTS, NAME_SEGMENTS) VALUES (SEGMENTS_SEQ.NEXTVAL, 'Filmes');

INSERT INTO TB_BOT (ID_BOT, NAME_BOT, WELCOME_MSG, FAREWELL_MSG, DOWNTIME, DEFAULT_ANSWER) VALUES (BOT_SEQ.NEXTVAL, 'BOT teste', 'Bem-vindo', 'Tchau meu amor', 10,'Não sei o que eu estou fazendo');

























