INSERT INTO TB_SEGMENTS (ID_SEGMENTS, NAME_SEGMENTS) VALUES (SEGMENTS_SEQ.NEXTVAL, 'Viagens');
INSERT INTO TB_SEGMENTS (ID_SEGMENTS, NAME_SEGMENTS) VALUES (SEGMENTS_SEQ.NEXTVAL, 'Comida');
INSERT INTO TB_SEGMENTS (ID_SEGMENTS, NAME_SEGMENTS) VALUES (SEGMENTS_SEQ.NEXTVAL, 'Videogames');
INSERT INTO TB_SEGMENTS (ID_SEGMENTS, NAME_SEGMENTS) VALUES (SEGMENTS_SEQ.NEXTVAL, 'Filmes');

INSERT INTO TB_BOT (ID_BOT, NAME_BOT, WELCOME_MSG, FAREWELL_MSG, DOWNTIME, DEFAULT_ANSWER) VALUES (BOT_SEQ.NEXTVAL, 'GooBoot', 'Bem-vindo', 'Ate mais', 10,'Infelizmento eu ainda nao conheco sobre este assunto');

























